### ISSUE TITLE
Passing spec

### ISSUE THREAD

**Issue by kbrock** [colby-swandale/waterfoul#1]
Hello Colby,

Very fun project.

Had a few ideas to speed this up, but would feel more comfortable if the tests were passing.

Any suggestions on getting the specs to pass.
Do you know if they are is a) unimplemented features, b) broken code, or c) broken tests?

Thanks

**Comment by colby-swandale** [comment]
HI @kbrock, thanks for the report. Sadly due to my laziness the tests are a bit of a lost child, during development i was rarely updating the specs and they have gotten old and as you have reported, breaking.

I am taking a look at them now and fixing/removing what i can to a satisfactory manner.

**Comment by colby-swandale** [comment]
Hi @kbrock,
I have updated the specs and should all be passing. Can you verify on your machine with `rspec`?

**Comment by kbrock** [comment]
Perfect. thanks.

I'll see if some ideas keep these passing.

Agreed that time is limited and too many side projects...
